name: Markdown Linter
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:      
  linting:
    name: Markdown Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Markdown
        uses: Adzz/yarn_command_action@v2.0.0
        with:
          package-manager: npm
          command: run lint
